[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["admin/**", "data/**", "images/**", "brands/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
